Repository metrodroid/metrodroid, pull requests merged in 2019-11, with the labels that each got.

#688 orca: Fix Seattle Monorail, show raw data flelds
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/orca/OrcaTransaction.kt
Labels: enhancement, new data

#706 Update the name for International District
  data/orca/stations.csv
  mdst/orca.mdst
Labels: new data

#704 Docs for broken java/windows unicode stuff
  jvmcli/windows.md
Labels: cleanup

#702 Add 5 more stops in Dublin, Ireland.
  data/tfi_leap/mapping_irishrail.csv
  data/tfi_leap/mapping_luas.csv
  mdst/tfi_leap.mdst
Labels: new data

#696 Add lint check to travis
  .travis.yml
  build.gradle
Labels: cleanup

#697 tampere: Add route and support for single-use cards
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/hsl/HSLArvo.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/hsl/HSLLookup.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/hsl/HSLTransaction.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/hsl/HSLUltralightTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/tampere/TampereTransitData.kt
Labels: enhancement, new card
