Repository metrodroid/metrodroid, pull requests merged in 2019-10, with the labels that each got.

#641 ricaricami: few additions to databases
  data/ricaricami/Makefile
  data/ricaricami/stations.csv
  mdst/ricaricami.mdst
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/ricaricami/RicaricaMiLookup.kt
  src/main/res/values/strings.xml
Labels: new data

#642 Change file import to use the same code as key import on pre-Kitkat
  src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt
  src/main/java/au/id/micolous/metrodroid/fragment/KeysFragment.kt
  src/main/java/au/id/micolous/metrodroid/util/Utils.kt
Labels: enhancement

#643 Updates to dependencies (Gradle 5.4.1)
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: cleanup

#647 Return Month in getMonth rather than a number
  src/commonMain/kotlin/au/id/micolous/metrodroid/time/Timestamp.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/lisboaviva/LisboaVivaSubscription.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/tfi_leap/LeapTransitData.kt
  src/jvmCommonTest/kotlin/au/id/micolous/metrodroid/test/DateTest.kt
Labels: enhancement

#648 Export bundle when exporting the keys
  src/commonMain/kotlin/au/id/micolous/metrodroid/key/ClassicKeysImpl.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/key/ClassicSectorKey.kt
Labels: bug

#649 Cli: show vehicle ID
  src/jvmCliMain/kotlin/au/id/micolous/metrodroid/Cli.kt
Labels: enhancement

#653 TreeListFragment: Use TextViewCompat.setTextAppearance
  src/main/java/au/id/micolous/metrodroid/fragment/TreeListFragment.kt
Labels: cleanup

#654 CardInfoActivity: Use newer speak function on post-Lollipop
  src/main/java/au/id/micolous/metrodroid/activity/CardInfoActivity.kt
Labels: cleanup

#655 Use PackageInfoCompat.getLongVersionCode instead of deprecated field
  src/main/java/au/id/micolous/metrodroid/activity/AboutActivity.kt
  src/main/java/au/id/micolous/metrodroid/util/Utils.kt
Labels: cleanup

#657 gradle: Add missing parameters for unsigned types in kotlin
  build.gradle
Labels: cleanup

#658 IntercodeLookupNavigo: rename parameter to match parent
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/intercode/IntercodeLookupNavigo.kt
Labels: cleanup

#659 Fix several warnings in tests
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/CardTest.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/ClassicReaderTest.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/EasyCardTest.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/ImportKeysTest.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/MRTReaderTest.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/OctopusTest.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/OrcaTest.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/StationTableReaderTest.kt
Labels: cleanup

#652 TripMap: Don't use deprecated WebViewFragment
  src/main/java/au/id/micolous/metrodroid/activity/TripMapActivity.kt
  src/main/java/au/id/micolous/metrodroid/fragment/TripMapFragment.kt
  src/main/res/layout/activity_trip_map.xml
Labels: cleanup

#650 Stretch a safety net under rendering of supported card
  src/main/java/au/id/micolous/metrodroid/fragment/CardBalanceFragment.kt
  src/main/java/au/id/micolous/metrodroid/fragment/SupportedCardsFragment.kt
  src/main/java/au/id/micolous/metrodroid/util/Utils.kt
Labels: bug

#656 CardsFragment: Supress deprecation warning in pre-KitKat code
  src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt
Labels: cleanup

#666 gautrain: Add coordinates to stations
  data/gautrain/stations.csv
  mdst/gautrain.mdst
Labels: new data

#664 compass: Update station names and add coordinates
  data/compass/stations.csv
  mdst/compass.mdst
Labels: new data

#663 amiibo: split file by class
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/amiibo/AmiiboTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/amiibo/AmiiboTransitFactory.kt
Labels: cleanup

#661 Switch from ProgressDialog to ProgressBar
  src/main/java/au/id/micolous/metrodroid/activity/FragmentWrapperActivity.kt
  src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt
  src/main/java/au/id/micolous/metrodroid/key/InsertKeyTask.kt
  src/main/java/au/id/micolous/metrodroid/util/BetterAsyncTask.kt
  src/main/res/layout/activity_add_key.xml
  src/main/res/layout/activity_fragment_wrapper.xml
Labels: cleanup

#651 CardTripsFragment: Use localizeFormatted rather than adding LocaleSpan.
  src/main/java/au/id/micolous/metrodroid/fragment/CardTripsFragment.kt
Labels: cleanup

#665 touchngo: Add coordinates and station codes
  data/touchngo/stations.csv
  mdst/touchngo.mdst
Labels: new data

#667 oura: Add coordinates
  data/oura/stations.csv
  mdst/oura.mdst
Labels: new data

#670 travis: limit JVM to 1.5G RAM
  .travis.yml
Labels: bug

#672 ios: fix getMonth usage after PR#647
  src/iOSMain/kotlin/au/id/micolous/metrodroid/time/Timestamp.kt
Labels: bug

#673 csv2pb: add "mode" column to Lines, move Line code to mdst.py
  extra/mdst/csv2pb.py
  extra/mdst/mdst.py
Labels: enhancement

#674 Add TransportType.MONORAIL, add missing TransportType.TOLL_ROAD to iOS
  native/metrodroid/metrodroid/Assets.xcassets/car.imageset/Contents.json
  native/metrodroid/metrodroid/Assets.xcassets/car.imageset/car.png
  native/metrodroid/metrodroid/Assets.xcassets/car.imageset/car_2x.png
  native/metrodroid/metrodroid/Assets.xcassets/car.imageset/car_3x.png
  native/metrodroid/metrodroid/Assets.xcassets/monorail.imageset/Contents.json
  native/metrodroid/metrodroid/Assets.xcassets/monorail.imageset/monorail.png
  native/metrodroid/metrodroid/Assets.xcassets/monorail.imageset/monorail_2x.png
  native/metrodroid/metrodroid/Assets.xcassets/monorail.imageset/monorail_3x.png
  native/metrodroid/metrodroid/TripCell.swift
  proto/src/main/proto/stations.proto
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/Trip.kt
  src/main/res/drawable/monorail.xml
  src/main/res/values/strings.xml
  src/main/res/values/themes.xml
  third_party/noto-emoji.md
Labels: enhancement

#571 Add Greek spelling of Metrodroid
  src/main/res/values-el/strings.xml
Labels: enhancement, help wanted

#668 ravkav: Add coordinates
  data/ravkav/stations.csv
  mdst/ravkav.mdst
Labels: new data

#679 troika: use Mode.MONORAIL for monorail
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/troika/TroikaTrip.kt
Labels: cleanup

#683 jvmCliMain: remove unused deps
  build.gradle
Labels: cleanup

#669 adelaide: Add coordinates
  data/adelaide/stations.csv
  mdst/adelaide.mdst
Labels: new data

#684 ORCA: Fix CSV file issues
  data/orca_brt/stations.csv
  data/orca_streetcar/stations.csv
Labels: cleanup

#682 lisboa_viva: Add coordinates from OSM
  data/lisboa_viva/stations.csv
  mdst/lisboa_viva.mdst
Labels: new data

#676 ios: Workaround for reading multi-system FeliCa cards (issue #613)
  docs/ios.md
  native/metrodroid/metrodroid/SupportedCardsViewCell.swift
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaCard.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaReader.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaService.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaSystem.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/CardInfo.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/octopus/OctopusTransitData.kt
  src/commonTest/assets/felica/felica-empty-system.json
  src/commonTest/assets/felica/felica-skipped-service.json
  src/commonTest/assets/felica/felica-skipped-system-missing-services.json
  src/commonTest/assets/felica/felica-skipped-system.json
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/FelicaJsonImportTest.kt
  src/iOSMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaCardReaderIOS.kt
  src/jvmCommonTest/kotlin/au/id/micolous/metrodroid/test/FelicaXmlImportTest.kt
  src/main/java/au/id/micolous/metrodroid/activity/MainActivity.kt
  src/main/java/au/id/micolous/metrodroid/card/CardReader.kt
  src/main/java/au/id/micolous/metrodroid/util/Preferences.kt
  src/main/res/values/strings.xml
  src/main/res/xml/prefs.xml
Labels: bug, ios

#680 yargortrans: New card
  cardimages/android/drawable-hdpi/yargor.jpeg
  data/Makefile
  data/yargor/.gitignore
  data/yargor/Makefile
  data/yargor/lines.csv
  data/yargor/stations.csv
  mdst/yargor.mdst
  native/metrodroid/metrodroid/Cards.xcassets/yargor.imageset/Contents.json
  native/metrodroid/metrodroid/Cards.xcassets/yargor.imageset/yargor.jpeg
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicCardFactoryRegistry.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/yargor/YarGorSubscription.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/yargor/YarGorTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/yargor/YarGorTransitFactory.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/yargor/YarGorTrip.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/util/StationTableReader.kt
  src/main/res/values-ru/strings.xml
  src/main/res/values/strings.xml
Labels: new card

#687 mct_to_mfcdump.py: add null bytes when bytes are unknown
  extra/mct_to_mfcdump.py
Labels: bug

#689 Updated supported cards list for 3.0.0
  README.md
Labels: cleanup

#690 Market changelog for 3.0.0
  src/main/res/values/market.xml
Labels: enhancement

#692 mdst/tisseo: Add coordinates
  data/tisseo/stations.csv
  mdst/tisseo.mdst
Labels: new data

#693 mdst/gironde: Add coordinates
  data/gironde/stations.csv
  mdst/gironde.mdst
Labels: new data

#698 Add more stops in Dublin, Ireland.
  data/tfi_leap/mapping_irishrail.csv
  data/tfi_leap/mapping_luas.csv
  mdst/tfi_leap.mdst
Labels: new data
