Repository metrodroid/metrodroid, pull requests merged in 2019-09, with the labels that each got.

#593 OctopusTest: run test methods on card rather than FelicaCard
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/OctopusTest.kt
Labels: cleanup

#594 NfcV support for iOS
  docs/ios.md
  native/metrodroid/metrodroid/NFCReader.swift
  native/metrodroid/metrodroid/SupportedCardsViewController.swift
Labels: enhancement

#596 project: change path to gradlew
  native/metrodroid/metrodroid.xcodeproj/project.pbxproj
Labels: bug

#597 proto: Fix compilation error with Java 12
  proto/build.gradle
Labels: bug

#595 crc: Add a test CrcTest
  src/commonMain/kotlin/au/id/micolous/metrodroid/util/HashUtils.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/CrcTest.kt
Labels: cleanup

#599 Add tests and documentation for `jvmcli`.
  .travis.yml
  .travis/jvmcli_test.sh
  README.md
  jvmcli/README.md
  jvmcli/build.gradle
Labels: enhancement

#602 Enabled Brazilian Portuguese
  native/metrodroid/metrodroid.xcodeproj/project.pbxproj
Labels: enhancement

#598 en1545: Fix null date of birth
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/En1545FixedInteger.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/En1545Test.kt
Labels: bug

#604 Promote multiple classes to jvmCommon
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/CardProtocolUnsupportedException.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/UnsupportedTagException.kt
  src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/util/UtilsJvm.kt
  src/main/java/au/id/micolous/metrodroid/activity/AdvancedCardInfoActivity.kt
  src/main/java/au/id/micolous/metrodroid/card/AndroidCardTransceiver.kt
  src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt
  src/main/java/au/id/micolous/metrodroid/util/Utils.kt
Labels: cleanup

#605 Fix possible crash with TypefaceSpan on pre-P devices
  src/main/java/au/id/micolous/metrodroid/multi/FormattedString.kt
Labels: bug

#609 Uplift LeapUnlocker to jvmCommon
  src/commonMain/kotlin/au/id/micolous/metrodroid/util/Preferences.kt
  src/iOSMain/kotlin/au/id/micolous/metrodroid/util/Preferences.kt
  src/jvmCliMain/kotlin/au/id/micolous/metrodroid/transit/tfi_leap/LeapUnlocker.kt
  src/jvmCliMain/kotlin/au/id/micolous/metrodroid/util/Preferences.kt
  src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/transit/tfi_leap/LeapUnlocker.kt
  src/main/java/au/id/micolous/metrodroid/util/Preferences.kt
Labels: enhancement

#612 clipper: Mark Warm Springs as confirmed
  data/clipper/mapping_bart.csv
Labels: new data

#615 Add TPF card (serial-only)
  cardimages/android/drawable-hdpi/tpf_card.png
  native/metrodroid/metrodroid/Cards.xcassets/tpf_card.imageset/Contents.json
  native/metrodroid/metrodroid/Cards.xcassets/tpf_card.imageset/tpf_card.png
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardTransitRegistry.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/serialonly/TPFCardTransitData.kt
  src/main/res/values/strings.xml
Labels: new card

#616 collapsed_header: Flip on RTL layouts
  native/metrodroid/metrodroid/Assets.xcassets/collapsed_header.imageset/Contents.json
Labels: bug

#611 Fix crash when handling BCE dates
  src/commonMain/kotlin/au/id/micolous/metrodroid/time/Timestamp.kt
Labels: bug

#617 iOS: Fix compilation failure
  src/iOSMain/kotlin/au/id/micolous/metrodroid/util/Preferences.kt
Labels: bug

#618 Implement document-picker import
  native/metrodroid/metrodroid/HistoryViewController.swift
Labels: enhancement

#619 Support importing XML on iOS
  docs/ios.md
  native/metrodroid/metrodroid/CardPersister.swift
  native/metrodroid/metrodroid/HistoryViewController.swift
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/Card.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/multi/Misc.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/serializers/CardSerializer.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/serializers/XmlCardFormat.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/Subscription.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/TransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/util/Base64.kt
  src/iOSMain/kotlin/au/id/micolous/metrodroid/card/classic/PlusCardReaderIOS.kt
  src/iOSMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardReaderIOS.kt
  src/iOSMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaCardReaderIOS.kt
  src/iOSMain/kotlin/au/id/micolous/metrodroid/card/iso7816/ISO7816CardReaderIOS.kt
  src/iOSMain/kotlin/au/id/micolous/metrodroid/card/ultralight/UltralightCardReaderIOS.kt
  src/iOSMain/kotlin/au/id/micolous/metrodroid/transit/TransitDataStored.kt
  src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/serializers/NodeWrapperImpl.kt
  src/main/java/au/id/micolous/metrodroid/multi/Misc.kt
Labels: enhancement

#623 Support Cifial cards
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicCardFactoryRegistry.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/cifial/CifialTransitData.kt
  src/main/res/values/strings.xml
Labels: new card

#626 iOS: Remove metrodroid registration as "Open with" target
  native/metrodroid/metrodroid/Info.plist
Labels: cleanup, ios

#624 Show notices for compass, mobib, navigo, oura, ravkav
  data/compass/Makefile
  data/compass/NOTICE
  data/mobib/Makefile
  data/mobib/NOTICE
  data/navigo/Makefile
  data/navigo/NOTICE
  data/navigo/license.txt
  data/oura/Makefile
  data/oura/NOTICE
  data/oura/license.txt
  data/ravkav/Makefile
  data/ravkav/NOTICE
  data/ravkav/license.txt
  extra/mdst/csv2pb.py
  mdst/compass.mdst
  mdst/mobib.mdst
  mdst/navigo.mdst
  mdst/oura.mdst
  mdst/ravkav.mdst
Labels: bug

#627 Few strings imporvements
  native/metrodroid/metrodroid/SupportedCardsHeader.swift
  src/main/java/au/id/micolous/metrodroid/fragment/SupportedCardsFragment.kt
  src/main/res/values/strings.xml
Labels: cleanup

#622 Lisboa Viva improvements
  data/Makefile
  data/lisboa_viva/.gitignore
  data/lisboa_viva/Makefile
  data/lisboa_viva/license-prefix.txt
  data/lisboa_viva/license.txt
  data/lisboa_viva/lines.csv
  data/lisboa_viva/mapping.csv
  data/lisboa_viva/stations.csv
  extra/mdst/compile_stops_from_gtfs.py
  mdst/lisboa_viva.mdst
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/En1545Transaction.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/lisboaviva/LisboaVivaLookup.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/lisboaviva/LisboaVivaSubscription.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/lisboaviva/LisboaVivaTransaction.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/lisboaviva/LisboaVivaTransitData.kt
  src/main/res/values/strings.xml
Labels: enhancement, new data

#584 Replace and split issue templates. Update contributing information
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/cracking_keys.md
  .github/ISSUE_TEMPLATE/data.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/new_card_felica.md
  .github/ISSUE_TEMPLATE/new_card_iso7816.md
  .github/ISSUE_TEMPLATE/new_card_mifare_classic.md
  .github/ISSUE_TEMPLATE/new_card_mifare_desfire.md
  .github/ISSUE_TEMPLATE/new_card_mifare_ultralight.md
  .github/ISSUE_TEMPLATE/new_card_vicinity.md
  .github/ISSUE_TEMPLATE/new_card_zz_unknown.md
  .github/ISSUE_TEMPLATE/questions.md
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
Labels: cleanup

#625 iOS doc reshuffle
  .github/ISSUE_TEMPLATE/bug.md
  README.md
  docs/index.md
  docs/ios.md
Labels: cleanup, ios

#630 A lint pass
  src/commonMain/kotlin/au/id/micolous/metrodroid/key/CardKeys.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/multi/FormattedString.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/serializers/CardSerializer.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/serializers/FarebotJsonFormat.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/lisboaviva/LisboaVivaLookup.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/ovc/OVChipIndex.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/oyster/OysterTransaction.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/rkf/RkfLookup.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/snapper/SnapperTransaction.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/troika/TroikaPurse.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/troika/TroikaTrip.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/warsaw/WarsawTransitData.kt
  src/main/java/au/id/micolous/metrodroid/activity/AboutActivity.kt
  src/main/java/au/id/micolous/metrodroid/activity/AddKeyActivity.kt
  src/main/java/au/id/micolous/metrodroid/activity/AdvancedCardInfoActivity.kt
  src/main/java/au/id/micolous/metrodroid/activity/LicenseActivity.kt
  src/main/java/au/id/micolous/metrodroid/activity/MainActivity.kt
  src/main/java/au/id/micolous/metrodroid/activity/ReadingTagActivity.kt
  src/main/java/au/id/micolous/metrodroid/fragment/CardBalanceFragment.kt
  src/main/java/au/id/micolous/metrodroid/fragment/CardInfoFragment.kt
  src/main/java/au/id/micolous/metrodroid/fragment/CardTripsFragment.kt
  src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt
  src/main/java/au/id/micolous/metrodroid/fragment/ExpandableListFragment.kt
  src/main/java/au/id/micolous/metrodroid/fragment/KeysFragment.kt
  src/main/java/au/id/micolous/metrodroid/fragment/SupportedCardsFragment.kt
  src/main/java/au/id/micolous/metrodroid/fragment/TreeListFragment.kt
  src/main/java/au/id/micolous/metrodroid/key/CardKeysDB.kt
  src/main/java/au/id/micolous/metrodroid/key/CardKeysEmbed.kt
  src/main/java/au/id/micolous/metrodroid/key/InsertKeyTask.kt
  src/main/java/au/id/micolous/metrodroid/provider/CardDBHelper.kt
  src/main/res/values-fr/strings.xml
  src/main/res/values-nl/strings.xml
  src/main/res/values-ru/strings.xml
Labels: cleanup

#632 Fix couple of crashes on Jelly Bean
  src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt
  src/main/java/au/id/micolous/metrodroid/fragment/KeysFragment.kt
  src/main/res/layout/supported_card.xml
Labels: bug

#634 Fix timezone crash on iOS
  src/commonMain/kotlin/au/id/micolous/metrodroid/time/Timestamp.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/mobib/MobibTransaction.kt
  src/iOSMain/kotlin/au/id/micolous/metrodroid/time/Timestamp.kt
Labels: bug, ios

#631 roll forward dependency versions; externalise some dep versions
  build.gradle
  jvmcli/build.gradle
  proto/build.gradle
Labels: bug, cleanup

#639 Add few LUAS stops I have checked personally.
  data/tfi_leap/mapping_luas.csv
Labels: new data

#629 ios: Support farebot json import
  native/metrodroid/metrodroid/CardPersister.swift
  native/metrodroid/metrodroid/HistoryViewController.swift
  src/commonMain/kotlin/au/id/micolous/metrodroid/serializers/CardSerializer.kt
Labels: enhancement, ios

#633 A lint pass. Round 2
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/En1545Bitmap.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/En1545Parsed.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/En1545Repeat.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/nextfare/NextfareSubscription.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/pisa/PisaLookup.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/rkf/RkfTicket.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/suica/SuicaDBUtil.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/tmoney/TMoneyTrip.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/util/MD5.kt
  src/dev/AndroidManifest.xml
  src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/util/UtilsJvm.kt
  src/main/AndroidManifest.xml
  src/main/java/au/id/micolous/metrodroid/activity/AdvancedCardInfoActivity.kt
  src/main/java/au/id/micolous/metrodroid/activity/CardInfoActivity.kt
  src/main/java/au/id/micolous/metrodroid/activity/LicenseActivity.kt
  src/main/java/au/id/micolous/metrodroid/activity/PreferencesActivity.kt
  src/main/java/au/id/micolous/metrodroid/activity/ReadingTagActivity.kt
  src/main/java/au/id/micolous/metrodroid/activity/TripMapActivity.kt
  src/main/java/au/id/micolous/metrodroid/fragment/CardTripsFragment.kt
  src/main/java/au/id/micolous/metrodroid/fragment/SupportedCardsFragment.kt
  src/main/java/au/id/micolous/metrodroid/fragment/TreeListFragment.kt
  src/main/res/drawable/trolleybus.xml
  src/main/res/layout-v21/list_recursive.xml
  src/main/res/layout/activity_about.xml
  src/main/res/layout/activity_advanced_card_info.xml
  src/main/res/layout/activity_card_info.xml
  src/main/res/layout/activity_license.xml
  src/main/res/layout/activity_main.xml
  src/main/res/layout/activity_reading_tag.xml
  src/main/res/layout/list_header.xml
  src/main/res/layout/list_recursive.xml
  src/main/res/layout/subscription_item.xml
  src/main/res/layout/supported_card.xml
  src/main/res/layout/trip_item.xml
  src/main/res/values-de/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-pt-rBR/strings.xml
  src/main/res/values-ru/strings.xml
  src/main/res/values/strings.xml
  src/main/res/values/themes.xml
Labels: cleanup

#636 bonobus: several improvements
  data/Makefile
  data/cadiz/.gitignore
  data/cadiz/Makefile
  data/cadiz/lines.csv
  data/cadiz/stations.csv
  mdst/cadiz.mdst
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/bonobus/BonobusTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/bonobus/BonobusTransitFactory.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/bonobus/BonobusTrip.kt
Labels: enhancement

#638 octopus: Fix transition date; add month enum
  src/commonMain/kotlin/au/id/micolous/metrodroid/time/Timestamp.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/octopus/OctopusData.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/OctopusTest.kt
Labels: bug

#637 easycard: Add stations coordinates
  data/easycard/stationlist/scrape_coords.py
  data/easycard/stations.csv
  mdst/easycard.mdst
Labels: new data

#645 Specify months through the enum when possible
  src/commonMain/kotlin/au/id/micolous/metrodroid/time/Timestamp.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/kmt/KMTTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/opal/OpalSubscription.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/CardTest.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/CompassTest.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/En1545Test.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/HSLTest.kt
Labels: cleanup

#644 Fix-up MainActivity layout regression.
  src/main/res/layout/activity_main.xml
Labels: bug
