Repository metrodroid/metrodroid, pull requests merged in 2019-06, with the labels that each got.

#430 MainActivity: small identation fix
  src/main/java/au/id/micolous/metrodroid/activity/MainActivity.kt
Labels: cleanup

#431 MctCardImporter: import unauthorized blocks as such
  src/commonMain/kotlin/au/id/micolous/metrodroid/serializers/classic/MctCardImporter.kt
Labels: bug

#432 CardType: fix reverse lookups
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/CardType.kt
  src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt
Labels: bug

#437 Cleanup locked app list handling
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardReader.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardTransitFactory.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/unknown/UnauthorizedDesfireTransitData.kt
Labels: cleanup

#440 Calypso1545TransitData: Small style fix
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/Calypso1545TransitData.kt
Labels: cleanup

#436 Remove SmartRiderTrip
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/Transaction.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/TransactionTrip.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/smartrider/SmartRiderTagRecord.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/smartrider/SmartRiderTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/smartrider/SmartRiderTrip.kt
Labels: cleanup

#435 TransactionTrip: Skip topup transactions while merging.
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/Transaction.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/TransactionTrip.kt
Labels: bug

#428 New card: Intercard
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardTransitRegistry.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/settings/ValueDesfireFileSettings.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/intercard/IntercardTransitData.kt
  src/main/res/values/strings.xml
Labels: new card

#443 ClassicReader: record both keys if we used both
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicReader.kt
Labels: enhancement

#444 ListItemAdapter: Correctly handle missing text2
  src/main/java/au/id/micolous/metrodroid/fragment/ListItemAdapter.kt
Labels: bug

#442 Support Pisa Carta Mobile and corresponding Ultralight tickets
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/calypso/CalypsoRegistry.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/ultralight/UltralightTransitRegistry.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/pisa/PisaLookup.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/pisa/PisaSpecialEvent.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/pisa/PisaSubscription.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/pisa/PisaTransaction.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/pisa/PisaTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/pisa/PisaUltralightTransitData.kt
  src/main/res/values/strings.xml
Labels: new card

#445 Utils.getErrorMessage: Better handle null cases coming from jvm
  src/main/java/au/id/micolous/metrodroid/util/Utils.kt
Labels: bug

#446 Mobib improvements
  data/mobib/mapping.csv
  data/mobib/operators.csv
  mdst/mobib.mdst
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/Calypso1545TransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/mobib/MobibLookup.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/mobib/MobibSubscription.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/mobib/MobibTransaction.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/mobib/MobibTransitData.kt
Labels: enhancement

#447 Support Metromoney card from Tbilissi
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicCardFactoryRegistry.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/metromoney/MetroMoneyTransitData.kt
  src/main/res/values/strings.xml
Labels: new card

#448 multi_crc: add crc32 variants
  extra/multi_crc.py
Labels: enhancement

#450 Make Emv parser into a factory and add it to supported cards
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/emv/EmvCard.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/CardInfoRegistry.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/emv/EmvTransitData.kt
  src/main/res/values/strings.xml
Labels: enhancement

#453 mfcdump_convert: Add missing codecs wrapping
  extra/mfcdump_convert.py
Labels: bug

#458 Improve Clipper stations data
  data/clipper/stations.csv
Labels: new data

#460 New card: Nol Card from Dubai (serial-only)
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardTransitRegistry.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/serialonly/NolTransitData.kt
  src/main/res/values/strings.xml
Labels: new card

#461 BlankUltralightTransitData: Fix bug leading to false positives
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/unknown/BlankUltralightTransitData.kt
Labels: bug

#464 LocalizeGenerator: remove drawables list and properly declare inputs …
  build.gradle
  buildSrc/src/main/java/au/id/micolous/metrodroid/LocalizeGenerator.kt
Labels: cleanup

#456 Add test for Date code
  src/androidTest/java/au/id/micolous/metrodroid/test/DateTest.kt
Labels: enhancement

#434 New card: Oyster (UK) first-generation MIFARE Classic
  extra/oyster.svg
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicCardFactoryRegistry.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/time/Timestamp.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/TransitCurrency.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/oyster/OysterPurse.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/oyster/OysterRefill.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/oyster/OysterTransaction.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/oyster/OysterTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/oyster/OysterTravelPass.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/oyster/OysterUtils.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/util/ImmutableByteArray.kt
  src/main/res/drawable-hdpi/oyster_card.png
  src/main/res/values/strings.xml
Labels: new card

#475 Otago Go Card also includes Queenstown
  README.md
  docs/index.md
Labels: cleanup

#465 Show both keys in raw MFC view when available.
  src/androidTest/java/au/id/micolous/metrodroid/test/ClassicReaderTest.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicReader.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicSector.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicSectorValid.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/bonobus/BonobusTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/charlie/CharlieCardTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/kiev/KievTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/metromoney/MetroMoneyTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/podorozhnik/PodorozhnikTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/rkf/RkfTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/smartrider/SmartRiderTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/troika/TroikaHybridTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/util/HashUtils.kt
Labels: enhancement

#490 Fix license header referring to .java
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/bilhete_unico/BilheteUnicoSPRefill.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/intercard/IntercardTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/magnacarta/MagnaCartaTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/pisa/PisaSpecialEvent.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/pisa/PisaSubscription.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/pisa/PisaTransaction.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/pisa/PisaTransitData.kt
Labels: cleanup

#491 Add dexcount to build
  build.gradle
Labels: enhancement

#492 Remove @Throws annotation
  src/main/java/au/id/micolous/metrodroid/card/CardReader.kt
  src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt
  src/main/java/au/id/micolous/metrodroid/fragment/KeysFragment.kt
  src/main/java/au/id/micolous/metrodroid/key/InsertKeyTask.kt
  src/main/java/au/id/micolous/metrodroid/serializers/XmlPullParserIterator.kt
  src/main/java/au/id/micolous/metrodroid/util/BetterAsyncTask.kt
  src/main/java/au/id/micolous/metrodroid/util/ExportHelper.kt
Labels: cleanup

#493 kazan, cityunion: Use CardInfo name-resource based constructor
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/china/CityUnionTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/kazan/KazanTransitData.kt
Labels: cleanup

#494 Get UTF-8 charset from kotlin library rather than carrying the code o…
  src/main/java/au/id/micolous/metrodroid/activity/AddKeyActivity.kt
  src/main/java/au/id/micolous/metrodroid/fragment/KeysFragment.kt
  src/main/java/au/id/micolous/metrodroid/util/ExportHelper.kt
  src/main/java/au/id/micolous/metrodroid/util/Utils.kt
Labels: cleanup

#495 Add unsigned compile options
  build.gradle
Labels: cleanup

#498 mfcdump_convert: nicely-format key json
  extra/mfcdump_convert.py
Labels: enhancement
