Repository metrodroid/metrodroid, pull requests merged in 2019-07, with the labels that each got.

#502 ClassicSectorValid: Catch possible exceptions in ClassicAccessBits
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicSectorValid.kt
Labels: cleanup

#513 Remove ugly backticks
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/charlie/CharlieCardTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/En1545FixedInteger.kt
  src/main/java/au/id/micolous/metrodroid/ui/TabPagerAdapter.kt
  src/main/java/au/id/micolous/metrodroid/util/BetterAsyncTask.kt
  src/main/java/au/id/micolous/metrodroid/util/ExportHelper.kt
Labels: cleanup

#512 Fix mfcdump_convert
  extra/mfcdump_convert.py
Labels: bug

#503 Bring back "Share all" option
  src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt
  src/main/res/menu/cards_menu.xml
Labels: bug

#511 kazan: Read tagId from metadata rather than block 0
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/kazan/KazanTransitData.kt
Labels: bug

#508 Fix reading mfc dump inside a zip
  src/commonMain/kotlin/au/id/micolous/metrodroid/serializers/classic/MfcCardImporter.kt
Labels: bug

#504 slaccess: vectorize image
  src/main/res/drawable-hdpi/slaccess.png
  src/main/res/drawable/slaccess.xml
Labels: enhancement

#509 troika: Support Druzhinnik (neighbourhood watch) variant
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/troika/TroikaBlock.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/troika/TroikaHybridTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/troika/TroikaLayout2.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/troika/TroikaTransitData.kt
  src/main/res/values/strings.xml
Labels: enhancement

#517 umarsh: Add Sarov e-wallet id
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/umarsh/UmarshTransitData.kt
  src/main/res/values/strings.xml
Labels: enhancement

#518 mfc/mct: Improve handling of 7-byte UIDs
  src/commonMain/kotlin/au/id/micolous/metrodroid/serializers/classic/MctCardImporter.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/serializers/classic/MfcCardImporter.kt
Labels: enhancement

#524 Move tag lifecycle management to platform code and remove reconnect i…
  src/androidTest/java/au/id/micolous/metrodroid/test/ISO7816Test.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/AbstractProtocol.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/CardTransceiver.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaProtocol.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaReader.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaTransceiver.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/VirtualISO7816Card.kt
  src/main/java/au/id/micolous/metrodroid/card/AndroidCardTransceiver.kt
  src/main/java/au/id/micolous/metrodroid/card/CardReader.kt
Labels: cleanup

#526 Update kotlin version and related imports
  build.gradle
  src/commonMain/kotlin/au/id/micolous/metrodroid/key/CardKeys.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/key/ClassicKeysImpl.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/serializers/JsonKotlinFormat.kt
Labels: cleanup

#527 Always ignore BadTokenException
  src/main/java/au/id/micolous/metrodroid/activity/ReadingTagTask.kt
  src/main/java/au/id/micolous/metrodroid/util/Utils.kt
Labels: bug

#529 classic: Make all the factories `object` rather than `class`
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicCardFactoryRegistry.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/FallbackFactory.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/gautrain/GautrainTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/komuterlink/KomuterLinkTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/metromoney/MetroMoneyTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/otago/OtagoGoCardData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/serialonly/TartuTransitFactory.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/touchngo/TouchnGoTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/waikato/WaikatoCardData.kt
Labels: cleanup

#530 ClassicCard: fix edge cases with incomplete reads
  src/androidTest/java/au/id/micolous/metrodroid/test/ClassicCardTest.kt
  src/androidTest/java/au/id/micolous/metrodroid/test/ClassicManufacturerDataTest.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicCard.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/multi/FormattedString.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/ui/ListItem.kt
  src/commonTest/assets/mfc/mfc-incomplete0.json
  src/commonTest/assets/mfc/mfc-incomplete1.json
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/Utils.kt
Labels: crash

#522 KMT_EPOCH Fix
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/kmt/KMTTransitData.kt
Labels: bug

#533 amiibo: Check number of pages as an alternative to model
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/amiibo/AmiiboTransitData.kt
Labels: bug

#535 Trip.Mode: Rename description to contentDescription
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/Trip.kt
  src/main/java/au/id/micolous/metrodroid/fragment/CardTripsFragment.kt
Labels: cleanup
