Repository metrodroid/metrodroid, pull requests merged in 2021-01, with the labels that each got.

#745 Fix large font layout issues on Android
  build.gradle
  src/main/res/layout/activity_about.xml
  src/main/res/layout/activity_license.xml
  src/main/res/layout/activity_main.xml
  src/main/res/layout/subscription_item.xml
  src/main/res/values/attrs.xml
  src/main/res/values/themes.xml
  src/main/res/xml/prefs.xml
Labels: bug

#662 Switch to material design
  build.gradle
  src/main/res/layout/activity_about.xml
  src/main/res/layout/activity_main.xml
  src/main/res/values/attrs.xml
  src/main/res/values/themes.xml
Labels: enhancement

#712 Identify Japan IC cards
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaConsts.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaUtils.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/edy/EdyTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/suica/SuicaConsts.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/suica/SuicaTransitData.kt
  src/commonMain/kotlin/au/id/micolous/metrodroid/transit/suica/SuicaUtil.kt
  src/commonTest/kotlin/au/id/micolous/metrodroid/test/SuicaTest.kt
  src/main/res/values/strings.xml
Labels: enhancement, new data

#748 Kotlin 1.3.50
  build.gradle
  native/metrodroid/metrodroid.xcodeproj/project.pbxproj
  src/iOSMain/cinterop/stations.def
  src/iOSMain/kotlin/au/id/micolous/metrodroid/util/StationTableReader.kt
Labels: cleanup
